#!/usr/bin/env python3
"""Generate FINAL_CERTIFICATION_v2.md from live verification results."""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def run(cmd: list[str]) -> tuple[int, str]:
    proc = subprocess.run(
        cmd,
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode, out.strip()


def collect_status() -> dict:
    status: dict = {"dimensions": [], "commands": []}

    checks = [
        ("ARC Orchestrator", [sys.executable, "build/arc_orchestrator.py", "--verify"]),
        ("Cargo unit tests", ["cargo", "test", "--lib"]),
        ("Coq proofs", ["coqc", "proofs/double_proof.v"]),
        ("V2 verify", [sys.executable, "scripts/verify_v2.py"]),
    ]

    for name, cmd in checks:
        rc, out = run(cmd)
        status["commands"].append({"name": name, "rc": rc, "output_tail": out[-800:]})
        status["dimensions"].append({"name": name, "pass": rc == 0})

    fm = ROOT / "syntax" / "feature_matrix_v2.json"
    if fm.exists():
        data = json.loads(fm.read_text())
        status["feature_matrix"] = data.get("status", "UNKNOWN")
        status["innovations"] = len(data.get("v2_features", []))

    return status


def render(status: dict) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    all_pass = all(d["pass"] for d in status["dimensions"])
    seal = "A+ HARD GATE v2.0 — CERTIFIED" if all_pass else "VERIFICATION INCOMPLETE"

    lines = [
        "# Frontier Syntax v2.0 — Final Certification",
        "",
        f"**Generated:** {now}",
        f"**Seal:** {seal}",
        "",
        "## Verification Dimensions",
        "",
        "| Dimension | Status |",
        "|-----------|--------|",
    ]

    for dim in status["dimensions"]:
        mark = "✅ PASS" if dim["pass"] else "❌ FAIL"
        lines.append(f"| {dim['name']} | {mark} |")

    lines.extend(
        [
            "",
            "## Innovation Count",
            "",
            f"- Feature matrix: **{status.get('feature_matrix', 'N/A')}**",
            f"- Innovations verified: **{status.get('innovations', 0)}/7**",
            "",
            "## Command Log",
            "",
        ]
    )

    for cmd in status["commands"]:
        mark = "PASS" if cmd["rc"] == 0 else "FAIL"
        lines.append(f"### {cmd['name']} — {mark}")
        lines.append("")
        lines.append("```")
        lines.append(cmd["output_tail"] or "(no output)")
        lines.append("```")
        lines.append("")

    lines.extend(
        [
            "## Certification Statement",
            "",
            "This document was generated by `scripts/generate_final_certification.py` "
            "from live repository verification. All listed checks were executed at generation time.",
            "",
            "---",
            "",
            "*Frontier Syntax v2.0 — The Future of Computing*",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="FINAL_CERTIFICATION_v2.md")
    args = parser.parse_args()

    status = collect_status()
    content = render(status)
    out_path = ROOT / args.output
    out_path.write_text(content)
    print(f"✅ Wrote {out_path}")
    return 0 if all(d["pass"] for d in status["dimensions"]) else 1


if __name__ == "__main__":
    raise SystemExit(main())
